describe('Create new salon', () => {
  it('a salon should create in super admin panel', () => {
    cy.fixture('../fixtures/SuperAdmin/createNewSalon.json').then((NewSalonData) => {
      cy.login()
      cy.visit('/superadmin/salons')
      cy.get('[data-cy="new-salon"]', { timeout: 10000 }).as('NewSalonButton')
      cy.get('@NewSalonButton').should('exist').and('be.visible').click()
      cy.get('[data-cy="salon-title"]').type(NewSalonData.title)
      cy.get('[data-cy="salon-address"]').type(NewSalonData.address)
      cy.get('[data-cy="salon-first-name"]').type(NewSalonData.first_name)
      cy.get('[data-cy="salon-last-name"]').type(NewSalonData.last_name)
      cy.get('[data-cy="salon-email"]').type(NewSalonData.email)
      cy.get('[data-cy="salon-phone-number"]').type(NewSalonData.phone)
      cy.get('[data-cy="salon-canrad-account"]').type(NewSalonData.salon_canrad_account)
      cy.get('[data-cy="add-salon"]', {timeout: 10000 }).click()
      cy.contains('Salon was created successfully').should('be.visible')
      cy.contains('Cypress Salon', { timeout: 10000 }).should('be.visible').click()
    })
  })
})
