describe('Create Location', () => {
  it('should create a new location', () => {
    cy.fixture('../fixtures/AdminPanel/createLocations.json').then((NewLocationData) => {
      cy.loginAdminPanelClearSession()
      cy.visit('/mysalon/settings/locations')
      cy.get('[data-cy=add-location-admin]').click()
      cy.get('[data-cy=location-title]').type(NewLocationData.title)
      cy.get('[data-cy=location-province]').type(NewLocationData.province)
      cy.get('[data-cy=location-address]').type(NewLocationData.address)
      cy.wait(500) // Wait for the dropdown to appear
      cy.get('[role="option"]').contains('London').click()
      cy.get('[data-cy=location-postal-code]').type(NewLocationData.postalCode)
      cy.get('[data-cy=location-phone-number]').type(NewLocationData.phoneNumber)
      cy.get('[data-cy=location-email]').type(NewLocationData.email)
      cy.get('[data-cy="day-checkbox-wed"]').click()
      cy.get('[data-cy="day-checkbox-tue"]').click()
      cy.get('[data-cy="day-checkbox-thu"]').click()
      cy.get('[data-cy="day-checkbox-fri"]').click()
      cy.get('[data-cy="day-checkbox-sat"]').click()
      cy.get('input[type="file"]').should('exist').attachFile('AdminPanel/test_image.jpg')
      cy.get('[data-cy=create-location-button]').click()
      cy.contains( 'Location was created successfully').should('be.visible')
    })
  })
})
